version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  AfterInstall:
    - location: /bin/bash
      timeout: 300
      runas: ec2-user
      script: |
        GITHUB_REPO="Nagarajucts/Jmeterui"     
        GITHUB_TOKEN="REPO_TOKEN"
       # GitHub token with repo access
        GITHUB_WORKFLOW="jmeterui.yml"      
        REF="main"                             

        # Trigger GitHub Action via GitHub API
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          https://api.github.com/repos/$GITHUB_REPO/actions/workflows/$GITHUB_WORKFLOW/dispatches \
          -d '{"ref":"'"$REF"'"}'  
