#Docker configuration

name: Performance test
on:
  workflow_dispatch:
jobs:
 
  build:
 
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
     
    # - uses: docker/setup-buildx-action@v2
    - name: Build the Docker image  
      run: docker build --build-arg RUNNER_VERSION=2.319.1 -t nagarajucts/jmeterrepo:latest .
 
    - name: Push to Dockerhub
      run: docker push nagarajucts/jmeterrepo:latest .
 
    - name: Pull Docker image
      run: docker pull nagarajucts/jmeterrepo:latest .

      
