name: Run Jmeter Tests 

on:
  workflow_dispatch:

jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    env:
      JMETER_THREADS: 10
      JMETER_DURATION: 60
      JMETER_PATH: 'SampleAPI.jmx'
      
    name: JMeter Test Execution
    steps:      
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Create reports directory
      run: mkdir reports
      
      
    - name: Run JMeter Tests
      run: |
       chmod +x SampleAPI.jmx
       SampleAPI.jmx
       
       args: "-JPath=api/users?page=2 -e -o ./reports/html/"
        
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-results
        path: result.jtl
        if-no-files-found: error
        
    - name: Upload HTML Reports
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-reports
        path: reports
        if-no-files-found: error
