name: Run Jmeter Tests 

on:
  workflow_run:
    workflows: ["build runner image"]
    types:
      - completed

jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: JMeter Test Execution
    steps:      
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Create reports directory
      run: mkdir reports
      
    - name: Run JMeter Tests
      uses: QAInsights/PerfAction@v5.6.2
      with:
        test-plan-path: ./SampleAPI.jmx
        args: "-JPath=api/users?page=2 -e -o ./reports/html/"
        
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-results
        path: result.jtl
        if-no-files-found: error
        
    - name: Upload HTML Reports
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-reports
        path: reports
        if-no-files-found: error
