name: Performance test

on:
  workflow_run:
    workflows: ["docker.yml"]
    types:
      - completed

jobs:
  hello_world_job:
    runs-on: ecs-pt-runner

    steps:
    - name: Performance test
      run: echo "PTUIAutomation"
      
    #git checkout
    - uses: actions/checkout@v3
    
    - name: Print files
      run: ls

    - name: Performancce test
      run: jmeter -n -t ./SampleAPI.jmx -Jpath=api/users?page=1 -Jduration=110 -Jusers=10 -Jrampup=10 -l ./SampleAPIjtl.jtl
