name: Run Jmeter Tests 

on:
  workflow_dispatch:

jobs:
  jmeter_job:
    runs-on: self-hosted
    #env:
      #JMETER_THREADS: 10
      #JMETER_DURATION: 60
      #JMETER_PATH: 'SampleAPI.jmx'
      
    name: JMeter Test Execution
    steps:      
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Create reports directory
      run: mkdir reports
      
      
    - name: Run JMeter Tests
      run: |
       ls
       jmeter -n -t ./SampleAPI.jmx -Jpath=api/users?page=1 -Jduration=110 -Jusers=10 -Jrampup=10 -l ./SampleAPIjtl.jtl
       
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-results
        path: SampleAPIjtl.jtl
        if-no-files-found: error
        
        
    - name: Run JMeter Tests
      run: |
       ls
       jmeter -g ./SampleAPIjtl.jtl -o ./html_report
       
    - name: Upload HTML Reports
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-reports
        path: html_report
        if-no-files-found: error
